### ISSUE TITLE
Change the discover button

### ISSUE THREAD

**Issue by tgoslee** [Terra-Foundation-for-American-Art/Artnav#3]
Make the "eye" icon more intuitive.  

- add a hover to say preview or use a different icon or phrase in that space

Once the icon is clicked it should take the user into the preview mode with the navigation icons showing (giving the user the option to hide the navigation)
exit preview should stay the same

**Comment by t4ylorlpoulin** [comment]
Thanks, Trenisha @tgoslee -- we would like this backend edit to the "eye" icon. 

In addition, we'd like a similar but separate edit: the "Discover" button is only available to frontend users, and when they click on a link from WordPress we'd like the navigation (the small circles, and access to the sidebar) to be visible, instead of the user having to click "Discover" to make them appear. Perhaps the "Discover" button can then be reworded to say "Hide Navigation" so all the user can see is the object.

**Comment by tgoslee** [comment]
@t4ylorlpoulin @je321ss Here are the changes I made to test out live:
- added a hover to the eye icon that says "click to preview" It takes three seconds to appear
- Backend - When users click the eye icon it will take them to preview mode with navigation and points showing immediately. They have the option to hide everything in the nav bar.
- Frontend - When a user clicks the artwork title it takes them to preview mode with all points and navigation showing with the option to hide it.

**Comment by t4ylorlpoulin** [comment]
@tgoslee this looks so good! Exactly what we were hoping for. I also appreciate the "click to preview" hover. To my eye this is finished but I'll check in with Jess. Thanks!
